### PR TITLE
Bump Less.rb dep version to v2.3.0

### PR DESCRIPTION
**Pull request by viddo**
Make the gem work with latest version of https://github.com/cowboyd/less.rb that was just recently updated to work with [Less 1.3.3](https://github.com/cloudhead/less.js/blob/master/CHANGELOG.md#133)

### CODE REVIEW

**Comment by viddo** [comment]
Works fine on my machine™ and existing specs also seems to work fine:

```
viddo@aloria:~/sandbox/sprockets-less $ bundle exec rake spec
/Users/viddo/.rbenv/versions/1.9.3-p286/bin/ruby -S rspec ./spec/sprockets-less_spec.rb
Run options: exclude {:todo=>true, :broken=>true}
............

Finished in 0.42769 seconds
12 examples, 0 failures
```

**Comment by fmasuhr** [comment]
Please merge this one. It´s working well for me too.
Can´t use the newest Twitter Bootstrap version without this Less update.

**Comment by lloeki** [comment]
Thanks for the feedback, folks.

**Comment by lloeki** [comment]
v0.5.3 has been pushed to rubygems.org.

**Comment by fmasuhr** [comment]
Thanks :)

**Comment by viddo** [comment]
Big thanks! :+1:

**Pull request merged**
